### ISSUE TITLE
Selecting a soundfont path and loading an SF2 RMI in fluidsynth uses the main soundfont

### ISSUE THREAD

**Issue by spessasus** [stuerp/foo_midi#68]
## Description
Selecting a soundfont path and loading an SF2 RMI in fluidsynth uses the main soundfont instead of the embedded one.
Using BASSMIDI instead resolves this, the SF2 RMI plays normally.

## Steps to reproduce
1. Grab a GM soundfont like GeneralUserGS or FluidR3GM
2. Choose it in the "paths" menu
3. Add and enable fluidsynth as the synthesizer
4. Play an SF2 RMI with a custom soundfont like this one [Hybrid song 2_20.zip](https://github.com/user-attachments/files/17138609/Hybrid.song.2_20.zip)
5, The main soundfont is used. You hear harpsichord instead of the triangle lead.

## Environment
- Windows 10 64-bit
- foo_midi 2.15.1.0
- foobar 2.1.5
- fluidsynth 2.3.6

**Comment by stuerp** [comment]
Can you try again with the version that is about to be released (2.16)? Sounds OK to me.

**Comment by spessasus** [comment]
With fluidsynth 2.4.3 it *works,* but it's a clicky mess, constant clicks with the drums.

**Comment by stuerp** [comment]
Maybe later. I'm experimenting now with the pre-built FluidSynth.exe using only default settings to see if I can get the file playing correctly with the embedded soundfont on top of a basic GM soundfont.

**Comment by stuerp** [comment]
> You should try asking on the repo in the discussions section. I'm sure that they'll help.

No success with the exe. Is this the correct place: https://github.com/FluidSynth/fluidsynth/discussions

**Comment by spessasus** [comment]
Yes

**Comment by stuerp** [comment]
The lastet [alpha release](https://github.com/stuerp/foo_midi/releases/tag/v2.16.1.0-alpha1) should fix this.

**Comment by stuerp** [comment]
This release makes all the RMI's sound correct.

https://github.com/stuerp/foo_midi/releases/tag/v2.16.1.0-alpha4

**Comment by spessasus** [comment]
Great work Peter! Even Africa is working fine.

However, [ran.rmi.zip](https://github.com/user-attachments/files/19264759/ran.rmi.zip) (remove .zip, it's not an archive) clicks a lot at the start.
I've updated the fluidsynth binary to 2.4.3 but it did not fix the issue. Note that BASSMIDI and fluidsynth CLI work fine without clicks.

**Comment by stuerp** [comment]
I don't have any 'clicks' with FluidSynth. It sounds the same like BASS MIDI. Could it be a Wine thing?

**Comment by spessasus** [comment]
Maybe!
But, again, the fluidsynth CLI (i mean fludisynth.exe that I point to in foobar) doesn't click with the midi + sf2 file combo under wine.

Attaching the video for reference:
https://github.com/user-attachments/assets/c1c22fe1-e341-4a9c-a142-8518b5778373

**Comment by stuerp** [comment]
> Maybe! But, again, the fluidsynth CLI (i mean fludisynth.exe that I point to in foobar) doesn't click with the midi + sf2 file combo under wine.
> 
> Attaching the video for reference: https://github.com/user-attachments/assets/c1c22fe1-e341-4a9c-a142-8518b5778373

Confirmed. I had to isolate channel 10 to really hear the difference between BASS MIDI and FluidSynth. So far, no clue what may cause the click.

**Comment by stuerp** [comment]
Fixed in https://github.com/stuerp/foo_midi/releases/tag/v2.17.0.0

**Comment by spessasus** [comment]
Works great. Thank you!
